### ISSUE TITLE
pppos and sms

### ISSUE THREAD

**Issue by garudaonekh** [levkovigor/ppposclient#2]
Hi,
I use this library as PPPOS for MQTT and also to read incoming SMS. But as I know when it's in PPPos mode, it can't read SMS. In order to read SMS, I have to switch to AT mode. 

Do you have any advice on this?

**Comment by levkovigor** [comment]
@garudaonekh 

Check example, there are 2 functions: enterATModePPPOS and cancelATModePPPOS to switch between PPP and AT Modes

**Comment by garudaonekh** [comment]
yes, i have tried both. and they work. But I donot wnt to switch back and forth at regular interval. I think if we have an interrupt when SMS arrived then it is better

**Comment by levkovigor** [comment]
@garudaonekh 

RING pin on GSM module acts as a Ring Indicator. It is basically the ‘interrupt’ out pin from the module. It is by default high and will pulse low for 120ms when a call is received. It can also be configured to pulse when an SMS is received.

I've not tested this for SMS, so can't explain how to do it. Check user manual for GSM module.

**Comment by garudaonekh** [comment]
Thanks, your suggestion worked like a charm. It's default to RING but I can also make it worked with SMS.
