### ISSUE TITLE
Serial port response

### ISSUE THREAD

**Issue by klconur** [levkovigor/ppposclient#3]
Thanks for the library. I am trying to use it with Arduino IDE. I am sending AT command to my modem but I cannot get a response. I have tried with SoftwareSerial library and it works. I forked the library changed some parameters and the result is same. Is it compatible with Arduino IDE or what can cause to this issue? Do you have any idea?

**Comment by levkovigor** [comment]
@klconur This library is for ESP32 board in Arduino IDE. Check your connections and baudrate
