### ISSUE TITLE
how to call http get and post request

### ISSUE THREAD

**Issue by dhsont** [levkovigor/ppposclient#4]
Hi
i wanted to create http get and post request using ppp library 

how to do this ?

can i use httpclient library which i use  with wifi for esp32?

i want to get json response from server using get request and send  json data using post request.

Thanks for this library.
i wanted to use ppp library for long time.

**Comment by levkovigor** [comment]
@dhsont there is example file in library, you can check how to send simple GET request. POST request is practically same. You generate it as char *REQUEST.

[https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol)
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST)

**Comment by dhsont** [comment]
Thanks @levkovigor  

I am able to call simpleGetRequest() 

But it sometime connects and sometime stucks
```
08:03:41.624 -> PPPOS Started
08:03:41.624 -> Starting PPPOS... OK
08:03:50.933 -> Connecting...                       (Stucked Here)
```


if i try many times (with modem restart) it connects some time but can't get response body from server , may  i know how to get response body from following code ?
```
void simpleGetRequest(){
  if (!ppposClient.connected() ) {
          Serial.println("Connecting...");
           ppposClient.connect(WEB_SERVER, 80);
  }
  if (ppposClient.connected() ) {
           Serial.println("Connected");
           Serial.println(ppposClient.write(REQUEST, strlen(REQUEST)));
           while(ppposClient.available()){
            Serial.print((char)ppposClient.read());
           }
  }
}
```

If simpleGetRequest() works once and  if i again enter "get" in console it does not work next time.

**Comment by levkovigor** [comment]
@dhsont 

try this modification of **simpleGetRequest()** with connection retries and answer waiting timeouts:

```
void simpleGetRequest() {
  int _retries = 10;
  for (int i = 0; i < _retries; i++) {
    if (!ppposClient.connected()) {
      Serial.println("Connecting...");
      ppposClient.connect(WEB_SERVER, 80);
    } else {
      break;
    }
  }
  if (ppposClient.connected()) {
    Serial.println("Connected");
    Serial.println(ppposClient.write(REQUEST, strlen(REQUEST)));
    unsigned long _timeout = millis();
    while (millis() <= _timeout + 2000) {
      while (!ppposClient.available()) {
        if (millis() > _timeout + 3000) break;
      }
      while (ppposClient.available()) {
        Serial.print((char) ppposClient.read());
        _timeout = millis();
      }
    }
  }
}
```

**Comment by levkovigor** [comment]
@dhsont Hi, did you test last solution? Is it works for you? Can I close this issue?
